spring:
  application:
    name: coffee
  data:
    web:
      pageable:
        max-page-size: 50
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coffee?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

server:
  port: 8080

